@startuml "sequence_diagram_masuk"

    title "Keluar"
    hide footbox
    skinparam  shadowing false

    ' frontend component
    actor "Penyelenggara Event" as eo   
    participant "__:EventListScreen__" as view1
    participant "__:AuthController__" as controller1
    participant "__:SharedPreferences__" as prefs
    
    eo -> view1: Membuka menu navigasi
    activate eo
    activate view1
    view1 --> eo: Menampilkan menu navigasi
    eo -> view1: Menekan tombol keluar
    view1 -> eo: Menampilkan dialog konfirmasi keluar
    alt menekan tombol ya
        eo -> view1: Menekan tombol ya
        view1 -> controller1: .logout()
        activate controller1
        controller1 -> prefs: .remove(token)
        activate prefs
        controller1 --> view1: dispose
        view1 --> eo: Menampilkan halaman masuk
    else menekah tombol tidak
        eo -> view1: Menekan tombol tidak
        view1 -> controller1: .back()
        controller1 --> view1: dispose
        view1 --> eo: Menutup dialog konfirmasi keluar
    end
    
@enduml