@startuml "activity_diagram_keluar"

title "Keluar"

|Pengelola Event|
    start
    :Membuka menu navigasi;
|Sistem|
    :Menampilkan menu navigasi;
|Pengelola Event|
    :Menekan tombol keluar;
|Sistem|
    :Menampilkan dialog konfirmasi;
    if () then (Menekan tombol ya)
        end 
    else (Menekan tombol tidak)
        :Menghapus data token autentikasi;
        :Mengarahkan ke halaman masuk;
        stop

@enduml